name: build
"on":
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: Build artifacts
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/*.jar